image: ruby:3.4.2

definitions:
  caches:
    bundler: ./vendor
  services:
    redis:
      image: redis
      memory: 512
    postgres:
      image: postgres
      environment:
        POSTGRES_DB: $DB_TEST
        POSTGRES_USER: $DB_USER
        POSTGRES_PASSWORD: $DB_PASSWORD

  steps:
    - step: &install-dependencies-and-run-tests
        name: Linter and Specs
        caches:
          - bundler
        script:
          - apt-get update && apt-get install -y xclip
          - bundle install
          - bundle exec rubocop
          - bundle exec rspec
        services:
          - redis
          - postgres
    - step: &deploy-to-production
        name: Deploy to Production
        image: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
        deployment: Production
        services:
          - docker
        script:
          - echo $GCP_SA_KEY | base64 -d > ${BITBUCKET_CLONE_DIR}/gcp-key.json
          - gcloud auth activate-service-account --key-file=${BITBUCKET_CLONE_DIR}/gcp-key.json
          - gcloud config set project $GCP_PROJECT_ID
          - gcloud auth configure-docker $GCP_LOCALE-docker.pkg.dev --quiet
          - docker build -t $ARTIFACT_REPOSITORY_NAME:$BITBUCKET_COMMIT .
          - docker tag $ARTIFACT_REPOSITORY_NAME:$BITBUCKET_COMMIT $GCP_LOCALE-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_ARTIFACT_REPO/$ARTIFACT_REPOSITORY_NAME:$BITBUCKET_COMMIT
          - docker push $GCP_LOCALE-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_ARTIFACT_REPO/$ARTIFACT_REPOSITORY_NAME:$BITBUCKET_COMMIT
          - gcloud container clusters get-credentials $GCP_CLUSTER_NAME --region $GCP_LOCALE --project $GCP_PROJECT_ID
          - export IMAGE_URL=$GCP_LOCALE-docker.pkg.dev/$GCP_PROJECT_ID/$GCP_ARTIFACT_REPO/$ARTIFACT_REPOSITORY_NAME:$BITBUCKET_COMMIT
          - sed -i "s|placeholder-image-tag|${IMAGE_URL}|g" k8/production/deployment.yaml
          - sed -i "s|placeholder-image-tag|${IMAGE_URL}|g" k8/production/cronjob.yaml
          - kubectl apply -f k8/production/deployment.yaml
          - kubectl apply -f k8/production/cronjob.yaml
pipelines:
  default:
    - step: *install-dependencies-and-run-tests
  branches:
    dev:
      - step: *install-dependencies-and-run-tests
    main:
      - step: *install-dependencies-and-run-tests
      - step: *deploy-to-production
