# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['POOL_SIZE'] %>
  username: <%= ENV['POSTGRES_USERNAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['HOST'] %>
  timeout: <%= ENV['TIMEOUT'] %>

development:
  <<: *default
  database: alpop_analysis_development

test:
  <<: *default
  database: alpop_analysis_test

production:
  <<: *default
  database: alpop_analysis_production
