class CreateResearchAndDevelopmentAnalysisItems < ActiveRecord::Migration[8.0]
  def change
    create_table :research_and_development_analysis_items do |t|
      t.string :analysis_items_cpf, index: { name: :r_n_d_analysis_item_cpf_index }
      t.integer :analysis_items_status
      t.integer :analysis_items_error_status
      t.datetime :analysis_items_created_at
      t.integer :analysis_items_analysis_report_id, index: { name: :r_n_d_analysis_report_id_index }
      t.integer :analysis_items_payment_situation, index: { name: :r_n_d_payment_situation_index }
      t.string :analysis_items_name
      t.integer :analysis_item_disapproval_situation
      t.integer :analysis_item_clone_of_id, index: { name: :r_n_d_clone_of_id_index }
      t.string :bv_acerta_essencials_cpf
      t.integer :bv_acerta_essencials_credit_type
      t.string :bv_acerta_essencials_consumer_type
      t.integer :bv_acerta_essencials_consumer_id
      t.jsonb :bv_additional_informations
      t.jsonb :bv_debits
      t.jsonb :bv_protested_titles
      t.string :bv_protested_title_summaries_register_size
      t.string :bv_protested_title_summaries_register_type
      t.string :bv_protested_title_summaries_register
      t.string :bv_protested_title_summaries_total
      t.string :bv_protested_title_summaries_initial_period
      t.string :bv_protested_title_summaries_final_period
      t.string :bv_protested_title_summaries_currency
      t.string :bv_protested_title_summaries_accumulated_value
      t.string :bv_protested_title_summaries_federative_unit
      t.integer :bv_protested_title_summaries_boa_vista_acerta_essencial_id
      t.string :bv_identifications_register_size
      t.string :bv_identifications_register
      t.string :bv_identifications_document
      t.string :bv_identifications_name
      t.string :bv_identifications_mother_name
      t.string :bv_identifications_birth_date
      t.string :bv_identifications_rg_number
      t.string :bv_identifications_emitting_organ
      t.string :bv_identifications_rg_federative_unit
      t.string :bv_identifications_rg_emitting_date
      t.string :bv_identifications_consulted_gender
      t.string :bv_identifications_birth_city
      t.string :bv_identifications_marital_status
      t.string :bv_identifications_dependent_number
      t.string :bv_identifications_educational_level
      t.string :bv_identifications_revenue_situation
      t.string :bv_identifications_update_date
      t.string :bv_identifications_cpf_zone
      t.string :bv_identifications_voter_title
      t.string :bv_identifications_death
      t.integer :bv_identifications_boa_vista_acerta_essencial_id
      t.string :bv_debit_occurrences_register_size
      t.string :bv_debit_occurrences_register_type
      t.string :bv_debit_occurrences_register
      t.string :bv_debit_occurrences_total_debtor
      t.string :bv_debit_occurrences_total_guarantor
      t.string :bv_debit_occurrences_accumulated_value
      t.string :bv_debit_occurrences_first_debit_date
      t.string :bv_debit_occurrences_first_debit_value
      t.string :bv_debit_occurrences_biggest_debit_date
      t.string :bv_debit_occurrences_biggest_debit_value
      t.integer :bv_debit_occurrences_boa_vista_acerta_essencial_id
      t.string :bv_locations_register_size
      t.string :bv_locations_register_type
      t.string :bv_locations_register
      t.string :bv_locations_public_place_type
      t.string :bv_locations_public_place_name
      t.string :bv_locations_public_place_number
      t.string :bv_locations_complement
      t.string :bv_locations_neighborhood
      t.string :bv_locations_city
      t.string :bv_locations_federative_unit
      t.string :bv_locations_zip_code
      t.string :bv_locations_ddd_1
      t.string :bv_locations_phone_1
      t.string :bv_locations_ddd_2
      t.string :bv_locations_phone_2
      t.string :bv_locations_ddd_3
      t.string :bv_locations_phone_3
      t.integer :bv_locations_boa_vista_acerta_essencial_id
      t.jsonb :bv_previous_queries
      t.string :bv_cheque_additional_informations_register_size
      t.string :bv_cheque_additional_informations_register_type
      t.string :bv_cheque_additional_informations_register
      t.string :bv_cheque_additional_informations_document_type
      t.string :bv_cheque_additional_informations_document_number
      t.string :bv_cheque_additional_informations_text
      t.string :bv_cheque_additional_informations_type_of_register
      t.integer :bv_cheque_additional_informations_boa_vista_acerta_essencial_id
      t.string :bv_current_account_historics_register_size
      t.string :bv_current_account_historics_register_type
      t.string :bv_current_account_historics_register
      t.string :bv_current_account_historics_bank
      t.string :bv_current_account_historics_agency
      t.string :bv_current_account_historics_current_account
      t.string :bv_current_account_historics_document_type
      t.string :bv_current_account_historics_document_number
      t.string :bv_current_account_historics_consultation_date
      t.string :bv_current_account_historics_consultation_hour
      t.integer :bv_current_account_historics_boa_vista_acerta_essencial_id
      t.string :bv_decisions_register_size
      t.string :bv_decisions_register_type
      t.string :bv_decisions_register
      t.string :bv_decisions_document_type
      t.string :bv_decisions_document
      t.string :bv_decisions_score
      t.string :bv_decisions_approves
      t.string :bv_decisions_text
      t.integer :bv_decisions_boa_vista_acerta_essencial_id
      t.string :bv_zip_code_confirmations_register_size
      t.string :bv_zip_code_confirmations_register_type
      t.string :bv_zip_code_confirmations_register
      t.string :bv_zip_code_confirmations_zip_code
      t.string :bv_zip_code_confirmations_address
      t.string :bv_zip_code_confirmations_neighborhood
      t.string :bv_zip_code_confirmations_city
      t.string :bv_zip_code_confirmations_federative_unit
      t.integer :bv_zip_code_confirmations_boa_vista_acerta_essencial_id
      t.string :bv_documents_names_register_size
      t.string :bv_documents_names_register_type
      t.string :bv_documents_names_register
      t.string :bv_documents_names_name
      t.string :bv_documents_names_birth_date
      t.string :bv_documents_names_document_type
      t.string :bv_documents_names_document_number
      t.string :bv_documents_names_document_2
      t.string :bv_documents_names_document_3
      t.integer :bv_documents_names_boa_vista_acerta_essencial_id
      t.jsonb :bv_list_of_returns_reported_by_ccfs
      t.string :bv_returns_reported_by_users_register_size
      t.string :bv_returns_reported_by_users_register_type
      t.string :bv_returns_reported_by_users_register
      t.string :bv_returns_reported_by_users_document_type
      t.string :bv_returns_reported_by_users_document
      t.string :bv_returns_reported_by_users_bank
      t.string :bv_returns_reported_by_users_agency
      t.string :bv_returns_reported_by_users_current_account
      t.string :bv_returns_reported_by_users_initial_cheque
      t.string :bv_returns_reported_by_users_final_cheque
      t.string :bv_returns_reported_by_users_reason
      t.string :bv_returns_reported_by_users_point
      t.string :bv_returns_reported_by_users_occurrence_date
      t.string :bv_returns_reported_by_users_register_date
      t.string :bv_returns_reported_by_users_currency
      t.string :bv_returns_reported_by_users_value
      t.string :bv_returns_reported_by_users_informant_code
      t.string :bv_returns_reported_by_users_informant
      t.string :bv_returns_reported_by_users_city
      t.string :bv_returns_reported_by_users_federative_unit
      t.integer :bv_returns_reported_by_users_boa_vista_acerta_essencial_id
      t.string :bv_cheques_stopped_for_reason21s_register_size
      t.string :bv_cheques_stopped_for_reason21s_register_type
      t.string :bv_cheques_stopped_for_reason21s_register
      t.string :bv_cheques_stopped_for_reason21s_document_type
      t.string :bv_cheques_stopped_for_reason21s_document_number
      t.string :bv_cheques_stopped_for_reason21s_bank
      t.string :bv_cheques_stopped_for_reason21s_agency
      t.string :bv_cheques_stopped_for_reason21s_current_account
      t.string :bv_cheques_stopped_for_reason21s_initial_cheque
      t.string :bv_cheques_stopped_for_reason21s_final_cheque
      t.string :bv_cheques_stopped_for_reason21s_point
      t.string :bv_cheques_stopped_for_reason21s_occurrence_date
      t.string :bv_cheques_stopped_for_reason21s_availability_date
      t.string :bv_cheques_stopped_for_reason21s_currency
      t.string :bv_cheques_stopped_for_reason21s_value
      t.string :bv_cheques_stopped_for_reason21s_informant
      t.integer :bv_cheques_stopped_for_reason21s_boa_vista_acerta_essencial_id
      t.string :bv_historic_informed_cheques_register_size
      t.string :bv_historic_informed_cheques_register_type
      t.string :bv_historic_informed_cheques_register
      t.string :bv_historic_informed_cheques_document_type
      t.string :bv_historic_informed_cheques_document_number
      t.string :bv_historic_informed_cheques_bank
      t.string :bv_historic_informed_cheques_agency
      t.string :bv_historic_informed_cheques_current_account
      t.string :bv_historic_informed_cheques_cheque
      t.string :bv_historic_informed_cheques_consultation_date
      t.string :bv_historic_informed_cheques_consultation_hour
      t.string :bv_historic_informed_cheques_network
      t.integer :bv_historic_informed_cheques_boa_vista_acerta_essencial_id
      t.string :bv_previous_cheque_consultations_register_size
      t.string :bv_previous_cheque_consultations_register_type
      t.string :bv_previous_cheque_consultations_register
      t.string :bv_previous_cheque_consultations_document_type
      t.string :bv_previous_cheque_consultations_document_number
      t.string :bv_previous_cheque_consultations_consultation_type
      t.string :bv_previous_cheque_consultations_credit_date
      t.string :bv_previous_cheque_consultations_credit_hour
      t.string :bv_previous_cheque_consultations_currency
      t.string :bv_previous_cheque_consultations_value
      t.string :bv_previous_cheque_consultations_informant
      t.integer :bv_previous_cheque_consultations_boa_vista_acerta_essencial_id
      t.string :bv_summary_of_returns_reported_by_users_register_size
      t.string :bv_summary_of_returns_reported_by_users_register_type
      t.string :bv_summary_of_returns_reported_by_users_register
      t.string :bv_summary_of_returns_reported_by_users_document_type
      t.string :bv_summary_of_returns_reported_by_users_document_number
      t.string :bv_summary_of_returns_reported_by_users_total
      t.string :bv_summary_of_returns_reported_by_users_first_devolution_date
      t.string :bv_summary_of_returns_reported_by_users_last_devolution_date
      t.integer :bv_summary_of_returns_reported_by_users_boa_vista_acerta_essencial_id
      t.jsonb :bv_score_rating_several_models
      t.string :bv_record_messages_register_size
      t.string :bv_record_messages_register_type
      t.string :bv_record_messages_register
      t.string :bv_record_messages_record_reference
      t.string :bv_record_messages_text
      t.integer :bv_record_messages_boa_vista_acerta_essencial_id
      t.string :bv_previous90_days_consultations_register_size
      t.string :bv_previous90_days_consultations_register_type
      t.string :bv_previous90_days_consultations_register
      t.string :bv_previous90_days_consultations_total
      t.string :bv_previous90_days_consultations_year_1
      t.string :bv_previous90_days_consultations_month_1
      t.string :bv_previous90_days_consultations_total_1
      t.string :bv_previous90_days_consultations_year_2
      t.string :bv_previous90_days_consultations_month_2
      t.string :bv_previous90_days_consultations_total_2
      t.string :bv_previous90_days_consultations_year_3
      t.string :bv_previous90_days_consultations_month_3
      t.string :bv_previous90_days_consultations_total_3
      t.string :bv_previous90_days_consultations_year_4
      t.string :bv_previous90_days_consultations_month_4
      t.string :bv_previous90_days_consultations_total_4
      t.integer :bv_previous90_days_consultations_boa_vista_acerta_essencial_id
      t.string :bv_cheque_stoppeds_register_size
      t.string :bv_cheque_stoppeds_register_type
      t.string :bv_cheque_stoppeds_register
      t.string :bv_cheque_stoppeds_occurrence_type
      t.string :bv_cheque_stoppeds_document_type
      t.string :bv_cheque_stoppeds_document_number
      t.string :bv_cheque_stoppeds_bank
      t.string :bv_cheque_stoppeds_agency
      t.string :bv_cheque_stoppeds_current_account
      t.string :bv_cheque_stoppeds_cheque
      t.string :bv_cheque_stoppeds_point
      t.string :bv_cheque_stoppeds_occurrence_date
      t.string :bv_cheque_stoppeds_availability_date
      t.string :bv_cheque_stoppeds_informant
      t.string :bv_cheque_stoppeds_indicator
      t.integer :bv_cheque_stoppeds_boa_vista_acerta_essencial_id
      t.string :bv_summary_devolution_reported_by_ccfs_register_size
      t.string :bv_summary_devolution_reported_by_ccfs_register_type
      t.string :bv_summary_devolution_reported_by_ccfs_register
      t.string :bv_summary_devolution_reported_by_ccfs_document_type
      t.string :bv_summary_devolution_reported_by_ccfs_document_number
      t.string :bv_summary_devolution_reported_by_ccfs_name
      t.string :bv_summary_devolution_reported_by_ccfs_names_total
      t.string :bv_summary_devolution_reported_by_ccfs_devolution_total
      t.string :bv_summary_devolution_reported_by_ccfs_reason_12
      t.string :bv_summary_devolution_reported_by_ccfs_reason_13
      t.string :bv_summary_devolution_reported_by_ccfs_reason_14
      t.string :bv_summary_devolution_reported_by_ccfs_reason_99
      t.integer :bv_summary_devolution_reported_by_ccfs_boa_vista_acerta_essencial_id
      t.string :bv_summary_previous_query_cheques_register_size
      t.string :bv_summary_previous_query_cheques_register_type
      t.string :bv_summary_previous_query_cheques_register
      t.string :bv_summary_previous_query_cheques_document_type
      t.string :bv_summary_previous_query_cheques_document_number
      t.string :bv_summary_previous_query_cheques_total
      t.string :bv_summary_previous_query_cheques_value
      t.string :bv_summary_previous_query_cheques_day
      t.string :bv_summary_previous_query_cheques_day_value
      t.string :bv_summary_previous_query_cheques_pre_dated
      t.string :bv_summary_previous_query_cheques_pre_dated_value
      t.integer :bv_summary_previous_query_cheques_boa_vista_acerta_essencial_id
      t.string :bv_phone_confirmations_register_size
      t.string :bv_phone_confirmations_register_type
      t.string :bv_phone_confirmations_register
      t.string :bv_phone_confirmations_area_code
      t.string :bv_phone_confirmations_phone
      t.string :bv_phone_confirmations_document_type
      t.string :bv_phone_confirmations_document_number
      t.string :bv_phone_confirmations_name
      t.string :bv_phone_confirmations_neighborhood
      t.string :bv_phone_confirmations_zip_code
      t.string :bv_phone_confirmations_city
      t.string :bv_phone_confirmations_federative_unit
      t.integer :bv_phone_confirmations_boa_vista_acerta_essencial_id
      t.string :bv_bank_branch_phones_addresses_register_size
      t.string :bv_bank_branch_phones_addresses_register_type
      t.string :bv_bank_branch_phones_addresses_register
      t.string :bv_bank_branch_phones_addresses_bank
      t.string :bv_bank_branch_phones_addresses_bank_name
      t.string :bv_bank_branch_phones_addresses_agency
      t.string :bv_bank_branch_phones_addresses_agency_name
      t.string :bv_bank_branch_phones_addresses_address
      t.string :bv_bank_branch_phones_addresses_neighborhood
      t.string :bv_bank_branch_phones_addresses_zip_code
      t.string :bv_bank_branch_phones_addresses_city
      t.string :bv_bank_branch_phones_addresses_federative_unit
      t.string :bv_bank_branch_phones_addresses_plaza
      t.string :bv_bank_branch_phones_addresses_area_code
      t.string :bv_bank_branch_phones_addresses_phone_1
      t.string :bv_bank_branch_phones_addresses_phone_2
      t.string :bv_bank_branch_phones_addresses_reserved
      t.integer :bv_bank_branch_phones_addresses_boa_vista_acerta_essencial_id
      t.string :idwall_reports_number
      t.integer :idwall_reports_status
      t.integer :idwall_reports_analysis_item_id
      t.string :idwall_cpfs_gender
      t.string :idwall_cpfs_number
      t.string :idwall_cpfs_birth_date
      t.string :idwall_cpfs_source
      t.string :idwall_cpfs_name
      t.string :idwall_cpfs_income
      t.string :idwall_cpfs_income_tax_situation
      t.string :idwall_cpfs_cpf_cadastral_situation
      t.string :idwall_cpfs_cpf_subscription_date
      t.string :idwall_cpfs_cpf_verifying_digit
      t.string :idwall_cpfs_year_of_death
      t.string :idwall_cpfs_social_name
      t.integer :idwall_cpfs_idwall_report_id
      t.jsonb :idwall_trials
      t.jsonb :idwall_addresses
      t.jsonb :idwall_related_people
      t.integer :ps_reports_analysis_item_id
      t.text :ps_reports_performed_searches
      t.jsonb :ps_trials
      t.jsonb :ps_family_assistances
      t.jsonb :ps_emergency_assistances
      t.jsonb :ps_monthly_benefits
      t.jsonb :ps_family_holdings
      t.jsonb :ps_bounced_checks
      t.jsonb :ps_commercial_relations
      t.jsonb :ps_criminal_antecedents
      t.string :ps_proprable_professions_codigo
      t.string :ps_proprable_professions_titulo
      t.string :ps_proprable_professions_numero_plugin
      t.integer :ps_proprable_professions_pro_analysis_id
      t.string :ps_presumed_salary_ranges_numero_plugin
      t.string :ps_presumed_salary_ranges_codigo_da_faixa_salarial
      t.string :ps_presumed_salary_ranges_faixa_salarial
      t.string :ps_presumed_salary_ranges_descricao_da_faixa
      t.integer :ps_presumed_salary_ranges_pro_analysis_id
      t.string :ps_presumed_incomes_numero_plugin
      t.string :ps_presumed_incomes_valor_da_renda_presumida
      t.integer :ps_presumed_incomes_pro_analysis_id
      t.string :bv_cadastrals_consumer_type
      t.integer :bv_cadastrals_consumer_id
      t.string :bv_basic_registrations_cpf
      t.string :bv_basic_registrations_name
      t.string :bv_basic_registrations_mother_name
      t.integer :bv_basic_registrations_boa_vista_cadastral_id
      t.date :bv_basic_registrations_birth_date
      t.boolean :bv_basic_registrations_exposed_person
      t.string :bv_basic_registrations_cpf_situation
      t.string :bv_cadastral_locations_cpf
      t.integer :bv_cadastral_locations_boa_vista_cadastral_id
      t.string :bv_cadastral_locations_emails
      t.jsonb :bv_addresses
      t.jsonb :bv_phones
      t.string :bv_cadastral_qualifications_cpf
      t.string :bv_cadastral_qualifications_death
      t.integer :bv_cadastral_qualifications_boa_vista_cadastral_id
      t.jsonb :bv_related_people
      t.integer :srs_fintech_reports_analysis_item_id
      t.string :srs_registrations_document_number
      t.string :srs_registrations_consumer_name
      t.string :srs_registrations_mother_name
      t.string :srs_registrations_birth_date
      t.string :srs_registrations_status_registration
      t.integer :srs_registrations_serasa_fintech_report_id
      t.date :srs_registrations_status_date
      t.string :srs_addresses_address_line
      t.string :srs_addresses_district
      t.string :srs_addresses_zip_code
      t.string :srs_addresses_country
      t.string :srs_addresses_city
      t.string :srs_addresses_state
      t.integer :srs_addresses_serasa_registration_id
      t.string :srs_phones_region_code
      t.string :srs_phones_area_code
      t.string :srs_phones_phone_number
      t.string :srs_phones_owner_type
      t.integer :srs_phones_owner_id
      t.integer :srs_negative_data_serasa_fintech_report_id
      t.integer :srs_pefins_serasa_negative_data_id
      t.jsonb :srs_negative_items
      t.integer :srs_summaries_count
      t.float :srs_summaries_balance
      t.string :srs_summaries_owner_type
      t.integer :srs_summaries_owner_id
      t.integer :srs_refins_serasa_negative_data_id
      t.integer :srs_notaries_serasa_negative_data_id
      t.jsonb :srs_notary_items
      t.integer :srs_checks_serasa_negative_data_id
      t.jsonb :srs_check_items
      t.integer :srs_scores_score
      t.string :srs_scores_score_model
      t.string :srs_scores_range
      t.string :srs_scores_default_rate
      t.integer :srs_scores_code_message
      t.string :srs_scores_message
      t.integer :srs_scores_serasa_fintech_report_id
      t.integer :srs_facts_serasa_fintech_report_id
      t.integer :srs_inquiries_serasa_fact_id
      t.jsonb :srs_inquiry_items
      t.integer :srs_stolen_documents_serasa_fact_id
      t.jsonb :srs_stolen_document_items
      t.integer :prv_big_data_corps_analysis_item_id
      t.string :prv_basic_data_tax_id_number
      t.string :prv_basic_data_tax_id_country
      t.string :prv_basic_data_name
      t.string :prv_basic_data_gender
      t.integer :prv_basic_data_name_word_count
      t.integer :prv_basic_data_number_of_full_name_namesakes
      t.integer :prv_basic_data_name_uniqueness_score
      t.integer :prv_basic_data_first_name_uniqueness_score
      t.integer :prv_basic_data_first_and_last_name_uniqueness_score
      t.datetime :prv_basic_data_birth_date
      t.integer :prv_basic_data_age
      t.string :prv_basic_data_zodiac_sign
      t.string :prv_basic_data_chinese_sign
      t.string :prv_basic_data_birth_country
      t.string :prv_basic_data_mother_name
      t.string :prv_basic_data_father_name
      t.string :prv_basic_data_marital_status_data
      t.string :prv_basic_data_tax_id_status
      t.string :prv_basic_data_tax_id_origin
      t.string :prv_basic_data_tax_id_fiscal_region
      t.boolean :prv_basic_data_has_obit_indication
      t.datetime :prv_basic_data_tax_id_status_date
      t.datetime :prv_basic_data_tax_id_status_registration_date
      t.datetime :prv_basic_data_creation_date
      t.datetime :prv_basic_data_last_update_date
      t.integer :prv_basic_data_provenir_big_data_corp_id
      t.integer :prv_alternative_id_numbers_provenir_basic_datum_id
      t.string :prv_alternative_id_numbers_document_type
      t.string :prv_alternative_id_numbers_document_number
      t.integer :prv_extended_document_informations_provenir_basic_datum_id
      t.string :prv_rgs_document_last4_digits
      t.datetime :prv_rgs_creation_date
      t.datetime :prv_rgs_last_update_date
      t.integer :prv_rgs_provenir_extended_document_information_id
      t.string :prv_rgs_number
      t.string :prv_sources_ENADE
      t.integer :prv_sources_provenir_rg_id
      t.string :prv_sources_state
      t.string :prv_aliases_common_name
      t.string :prv_aliases_standardized_name
      t.integer :prv_aliases_provenir_basic_datum_id
      t.integer :prv_extended_addresses_total_addresses
      t.integer :prv_extended_addresses_total_active_addresses
      t.integer :prv_extended_addresses_total_work_addresses
      t.integer :prv_extended_addresses_total_personal_addresses
      t.integer :prv_extended_addresses_total_unique_addresses
      t.integer :prv_extended_addresses_total_address_passages
      t.integer :prv_extended_addresses_total_bad_address_passages
      t.datetime :prv_extended_addresses_oldest_address_passage_date
      t.datetime :prv_extended_addresses_newest_address_passage_date
      t.integer :prv_extended_addresses_provenir_big_data_corp_id
      t.jsonb :prv_addresses
      t.integer :prv_extended_phones_total_phones
      t.integer :prv_extended_phones_total_active_phones
      t.integer :prv_extended_phones_total_work_phones
      t.integer :prv_extended_phones_total_personal_phones
      t.integer :prv_extended_phones_total_unique_phones
      t.integer :prv_extended_phones_total_phone_passages
      t.integer :prv_extended_phones_total_bad_phone_passages
      t.integer :prv_extended_phones_total_last3_months_passages
      t.integer :prv_extended_phones_total_last6_months_passages
      t.integer :prv_extended_phones_total_last12_months_passages
      t.integer :prv_extended_phones_total_last18_months_passages
      t.datetime :prv_extended_phones_oldest_phone_passage_date
      t.datetime :prv_extended_phones_newest_phone_passage_date
      t.integer :prv_extended_phones_provenir_big_data_corp_id
      t.integer :prv_extended_phones_total_last16_months_passages
      t.jsonb :prv_phones
      t.string :prv_financial_data_total_assets
      t.datetime :prv_financial_data_creation_date
      t.datetime :prv_financial_data_last_update_date
      t.integer :prv_financial_data_provenir_big_data_corp_id
      t.string :prv_income_estimates_mte
      t.string :prv_income_estimates_company_ownership
      t.string :prv_income_estimates_ibge
      t.string :prv_income_estimates_bigdata
      t.string :prv_income_estimates_bigdata_v2
      t.integer :prv_income_estimates_provenir_financial_datum_id
      t.jsonb :prv_tax_returns
      t.string :prv_financial_risks_total_assets
      t.string :prv_financial_risks_estimated_income_range
      t.boolean :prv_financial_risks_is_currently_employed
      t.boolean :prv_financial_risks_is_currently_owner
      t.datetime :prv_financial_risks_last_occupation_start_date
      t.boolean :prv_financial_risks_is_currently_on_collection
      t.integer :prv_financial_risks_last365_days_collection_occurrences
      t.integer :prv_financial_risks_current_consecutive_collection_months
      t.boolean :prv_financial_risks_is_currently_receiving_assistance
      t.integer :prv_financial_risks_financial_risk_score
      t.string :prv_financial_risks_financial_risk_level
      t.integer :prv_financial_risks_provenir_big_data_corp_id
      t.integer :prv_processes_provenir_big_data_corp_id
      t.integer :prv_processes_lawsuits_total
      t.integer :prv_processes_defendant_lawsuits_total
      t.integer :prv_processes_plaintiff_lawsuits_total
      t.jsonb :prv_lawsuits
      t.integer :prv_related_people_total_relationships
      t.integer :prv_related_people_total_relatives
      t.integer :prv_related_people_total_neighbors
      t.integer :prv_related_people_total_spouses
      t.integer :prv_related_people_total_coworkers
      t.integer :prv_related_people_total_household
      t.integer :prv_related_people_total_partners
      t.integer :prv_related_people_total_college_class
      t.integer :prv_related_people_provenir_big_data_corp_id
      t.jsonb :prv_personal_relationships
      t.boolean :prv_collections_is_currently_on_collection
      t.integer :prv_collections_last30_days_collection_occurrences
      t.integer :prv_collections_last90_days_collection_occurrences
      t.integer :prv_collections_last180_days_collection_occurrences
      t.integer :prv_collections_last365_days_collection_occurrences
      t.integer :prv_collections_last30_days_collection_origins
      t.integer :prv_collections_last90_days_collection_origins
      t.integer :prv_collections_last180_days_collection_origins
      t.integer :prv_collections_last365_days_collection_origins
      t.integer :prv_collections_total_collection_months
      t.integer :prv_collections_current_consecutive_collection_months
      t.integer :prv_collections_max_consecutive_collection_months
      t.datetime :prv_collections_first_collection_date
      t.datetime :prv_collections_last_collection_date
      t.integer :prv_collections_collection_occurrences
      t.integer :prv_collections_collection_origins
      t.integer :prv_collections_provenir_big_data_corp_id
      t.integer :prv_business_relationships_total_relationships
      t.integer :prv_business_relationships_total_ownerships
      t.integer :prv_business_relationships_total_employments
      t.integer :prv_business_relationships_total_partners
      t.integer :prv_business_relationships_total_clients
      t.integer :prv_business_relationships_total_suppliers
      t.integer :prv_business_relationships_provenir_big_data_corp_id
      t.jsonb :prv_business_relationships_items
      t.jsonb :predictions

      t.timestamps
    end
  end
end
